server:
  port: 8044

spring:
  application:
    name: live-service
  cloud:
    nacos:
      config:
        # nacos服务地址. 默认值localhost:8848
        server-addr: localhost:8848
        # 配置文件后缀(在bootstrap.yml或在bootstrap.properties配置文件中才会生效). 默认值properties
        # file-extension: yaml